packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - supabase
